apiVersion: v1
kind: Pod
metadata:
  name: kiada-init
spec:
  initContainers:
  - name: init-demo
    image: genedocker/init-demo:0.1
  - name: network-check
    image: genedocker/network-connectivity-checker:0.1
    args:
    - 8.8.8.8   # the IP that the network-connectivity-checker should ping
  containers:
  - name: kiada
    image: genedocker/kiada:0.2
    stdin: true
    ports:
    - name: http
      containerPort: 8080
  - name: envoy
    image: genedocker/kiada-ssl-proxy:0.1
    ports:
    - name: https
      containerPort: 8443
    - name: admin
      containerPort: 9901
